//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveCareCore.Data.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DriveCareDBEntities : DbContext
    {
        public DriveCareDBEntities()
            : base("name=DriveCareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<CarColors> CarColors { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<CarTypes> CarTypes { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<FuelTypes> FuelTypes { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<PartManufacturers> PartManufacturers { get; set; }
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserCars> UserCars { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WarehouseManagers> WarehouseManagers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
    }
}
