//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveCareCore.Data.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DriveCareDBEntities2 : DbContext
    {
        public DriveCareDBEntities2()
            : base("name=DriveCareDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<BusinessType> BusinessTypes { get; set; }
        public virtual DbSet<CarColor> CarColors { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarSalePrice> CarSalePrices { get; set; }
        public virtual DbSet<CarSale> CarSales { get; set; }
        public virtual DbSet<CarType> CarTypes { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EmployeeRolesMap> EmployeeRolesMaps { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FuelType> FuelTypes { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PartManufacturer> PartManufacturers { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PermissionGroup> PermissionGroups { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<RepairCategory> RepairCategories { get; set; }
        public virtual DbSet<RepairHistory> RepairHistories { get; set; }
        public virtual DbSet<RolePermissionsMap> RolePermissionsMaps { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<UserCar> UserCars { get; set; }
        public virtual DbSet<UserCarSale> UserCarSales { get; set; }
        public virtual DbSet<UserNotification> UserNotifications { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WarehouseManager> WarehouseManagers { get; set; }
        public virtual DbSet<Workshop> Workshops { get; set; }
    }
}
