//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveCareCore.Data.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceDocument()
        {
            this.ServiceDocumentPartLines = new HashSet<ServiceDocumentPartLine>();
            this.ServiceDocumentServiceLines = new HashSet<ServiceDocumentServiceLine>();
        }
    
        public System.Guid RowId { get; set; }
        public System.Guid RootTaskId { get; set; }
        public Nullable<System.Guid> RepairHistoryId { get; set; }
        public System.Guid WorkshopId { get; set; }
        public Nullable<System.Guid> CarId { get; set; }
        public Nullable<System.Guid> ClientUserId { get; set; }
        public string Title { get; set; }
        public string ClientName { get; set; }
        public string ClientPhone { get; set; }
        public string ClientEmail { get; set; }
        public string VisitReason { get; set; }
        public string SpecialNotes { get; set; }
        public string ServiceKind { get; set; }
        public string ReportText { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDocumentPartLine> ServiceDocumentPartLines { get; set; }
        public virtual Task Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDocumentServiceLine> ServiceDocumentServiceLines { get; set; }
    }
}
