//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveCareCore.Data.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOrder
    {
        public System.Guid RowId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid PickupPointId { get; set; }
        public string OrderNumber { get; set; }
        public byte Status { get; set; }
        public decimal TotalAmount { get; set; }
        public string QrPayload { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> PaidAt { get; set; }
    }
}
