//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveCareCore.Data.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public System.Guid RowId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid StatusId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.Guid> CarId { get; set; }
        public Nullable<System.Guid> ClientUserId { get; set; }
        public string ReportText { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
