//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveCareCore.Data.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCarComponentStatus
    {
        public System.Guid RowId { get; set; }
        public System.Guid UserCarRowId { get; set; }
        public string ComponentCode { get; set; }
        public byte StatusLevel { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<int> LastMileageKm { get; set; }
        public Nullable<int> RemainingKmHint { get; set; }
        public string ShortHint { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    }
}
