//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveCareCore.Data.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkshopConversation
    {
        public System.Guid RowId { get; set; }
        public System.Guid WorkshopId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> WorkshopServiceClientId { get; set; }
        public string Subject { get; set; }
        public System.DateTime LastMessageAt { get; set; }
        public string LastMessagePreview { get; set; }
        public int UnreadForUser { get; set; }
        public int UnreadForWorkshop { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
