//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveCareCore.Data.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkshopMessage
    {
        public System.Guid RowId { get; set; }
        public System.Guid ConversationId { get; set; }
        public byte SenderKind { get; set; }
        public Nullable<System.Guid> SenderUserId { get; set; }
        public Nullable<System.Guid> SenderEmployeeId { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
